### ISSUE TITLE
Only items appear in the editor

### ISSUE THREAD

**Issue by Deobulakenyo** [jim972329667/MonsterHunterStories2#2]
Only items appear in the latest version. all other elements are missing

**Comment by jim972329667** [comment]
Maybe your MHS2.db damaged

**Comment by Deobulakenyo** [comment]
What do you mean damaged? I downloaded your included db. then i loaded my save file?
 is editing different now from the previous editions?

**Comment by jim972329667** [comment]
Can you show me the screenshots

**Comment by Deobulakenyo** [comment]
Elvin R. Ventucillo
University Registrar
Baliuag University
Baliwag, Bulacan
(044)766-0399
***@***.***

**Comment by jim972329667** [comment]
I mean the screenshot of the program where you open the save file ....

**Comment by Deobulakenyo** [comment]
I don't understand your question.


Elvin R. Ventucillo
University Registrar
Baliuag University
Baliwag, Bulacan
(044)766-0399
***@***.***

**Comment by jim972329667** [comment]
![image](https://user-images.githubusercontent.com/59948910/127758357-4d1bbbd1-28e1-49cf-b21b-cec3338e6696.png)
Like this

I don't know what your problem is

**Comment by Deobulakenyo** [comment]
The save file is in the folder derived from Checkpoint.

I load it on your editor. the items appear with counts. all the other infor
like player character names and monsters are missing from the editor


Elvin R. Ventucillo
University Registrar
Baliuag University
Baliwag, Bulacan
(044)766-0399
***@***.***

**Comment by jim972329667** [comment]
![image](https://user-images.githubusercontent.com/59948910/127758505-4ce27e97-c720-40ad-bb3d-25740f8ffe78.png)

Don't click this button if your save file is Swicth

**Comment by Deobulakenyo** [comment]
Thanks


Elvin R. Ventucillo
University Registrar
Baliuag University
Baliwag, Bulacan
(044)766-0399
***@***.***
